### ISSUE TITLE
500 error on Gaia query

### ISSUE THREAD

**Issue by ttdu** [TeHanHunter/TESS_Gaia_Light_Curve#7]
the notebook tutorial produces a 500 error on running `convert_gaia_id`. the underlying cause of this function's error is `astroquery.Gaia` rejecting numpy strings in the catalog query. by running `Gaia.launch_job` (without `_async`), the error code becomes a much more helpful 400:
`HTTPError: Error 400: 
Cannot parse query '
            SELECT  TOP 2000 dr2_source_id, dr3_source_id
            FROM gaiadr3.dr2_neighbourhood
            WHERE dr2_source_id IN (np.str_('2738338626715215232'), np.str_('2546164884900574720'), ..........`

I have tglc 0.6.5, Python 3.12, and the latest dev version of astroquery (0.4.8.dev9474). I'm not sure what combination of these is responsible for the issue

in any case, [I've opened a PR](https://github.com/TeHanHunter/TESS_Gaia_Light_Curve/pull/8) with my (admittedly silly) work-around. avoiding numpy strings solved the problem, but I have done zero testing to make sure this doesn't break anything downstream

**Comment by TeHanHunter** [comment]
Hi, thanks for your input! Do you mind testing with astroquery 0.4.7? I've seen these errors with different versions of astroquery. Thanks!

**Comment by TeHanHunter** [comment]
I was able to reproduce this error on a new install in a new virtual environment. I don't have this problem on my older installations even if I use the same packages. It seems the input requirement to `Gaia.launch_job_async()` changed. Your PR works after some testing and I will accept it. I will also change it to a more compact version. Thanks for your help!
